---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - ./namespace.yaml
  - ./route.yaml
  # - externalsecret.yaml
  # - pvc.yaml
helmCharts:
  - name: kagent-crds
    repo: oci://ghcr.io/kagent-dev/kagent/helm
    version: 0.7.8
    releaseName: kagent-crds
    namespace: kagent
  - name: kagent
    repo: oci://ghcr.io/kagent-dev/kagent/helm
    version: 0.6.21
    releaseName: kagent
    namespace: kagent
    valuesFile: values.yaml
