controllers:
  firefly-importer:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: fireflyiii/data-importer
          tag: version-1.5.6
        resources:
          requests:
            cpu: 15m
            memory: 64Mi
        env:
          TZ: Europe/Zurich
          TRUSTED_PROXIES: "**"
          FIREFLY_III_URL: "http://firefly.banking.svc.cluster.local:8080"
          VANITY_URL: "https://money.pitower.link"
          CAN_AUTO_IMPORT: "true"
          CAN_POST_FILES: "true"
        envFrom:
          - secretRef:
              name: firefly-importer-secrets
service:
  app:
    controller: firefly-importer
    ports:
      http:
        port: 8080
route:
  app:
    hostnames:
      - money-import.pitower.link
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https
