---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - certificate.yaml
  - direct.yaml
  - external.yaml
  - internal.yaml
  - envoy.yaml
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.3
    releaseName: envoy-gateway
    namespace: networking
    valuesFile: values.yaml
    includeCRDs: true
