controllers:
  otbr:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      # Host network required for Thread mesh
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: worker-04
    containers:
      app:
        image:
          repository: openthread/otbr
          tag: latest
        env:
          TZ: Europe/Zurich
          # Sonoff dongle Thread RCP device
          RADIO_URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
          BACKBONE_INTERFACE: eth0
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN

service:
  app:
    controller: otbr
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 192.168.0.230
    ports:
      web:
        port: 80
      rest:
        port: 8081

route:
  app:
    hostnames:
      - otbr.pitower.link
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 80

persistence:
  usb:
    type: hostPath
    hostPath: /dev/ttyACM0
    hostPathType: ""
    globalMounts:
      - path: /dev/ttyACM0
